### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by piepieninja** [USGS-Astrogeology/GDAL_scripts#35]
When I run the `gdal2PLY.py` script I get the following error

```
  File "gdal2PLY.py", line 107, in <module>
    main(sys.argv[1:])
  File "gdal2PLY.py", line 101, in main
    vertices = createvertexarray(raster)
  File "gdal2PLY.py", line 77, in createvertexarray
    vertices = np.vstack((xx,yy,zz)).reshape([3, -1]).transpose()
  File "/usr/local/lib/python2.7/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input arrays must have same number of dimensions
```

**Comment by thareUSGS** [comment]
Unfortunately this hasn't been well tested across different file types. Thus I might need an example to test locally. Can you also test the DEM below?

Here is my environment (just listing gdal and numpy) under a Python 2.7 Anaconda environment (although I think Python 3.x should work), and installing:
conda install -c conda-forge gdal numpy

```
gdalinfo --version
GDAL 2.3.1, released 2018/06/22
```
or
```
python
>>> import gdal
>>> gdal.VersionInfo()
'2030100'
>>> import numpy
>>> numpy.__version__
'1.15.0'
```

Again, can you test this image?
wget https://pdsimage2.wr.usgs.gov/Missions/Mars_Express/mexhrsc_2001/data/2596/h2596_0001_da4.img

to run:
$ python gdal2PLY.py h2596_0001_da4.img h2596_0001_da4.ply

This ran for me and allowed me to open the resulting PLY in meshlab.
