### ISSUE TITLE
[WKT2/Proj6] : proposal for new IAU projection code pattern

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/GDAL_scripts#37]
Issue: solidify use of namespace, year and code for WKT2 verbose definitions and Proj6 incorporation.

**Current use:**  `pattern IAU<year>:<code>`
example: IAU2015:49900  (Mars)

**Proposal**  `pattern IAU:<year>:<code>`
example: IAU:2015:49900 (Mars)

This separates the IAU namespace from the year which helps with versioning and also RESTful endpoints for web services.

**Comment by thareUSGS** [comment]
+1 

I am fine with the update for WKT2 and PROJ6. Current implementations which might be impacted (Lunaserv, JMARS, Mapserver, maybe iMars).

**Comment by desruisseaux** [comment]
I would recommend the `IAU:<year>:<code>` pattern since the OGC URI syntax explicitly reserves the middle part for versioning. In WKT 2 it becomes `ID["IAU", <code>, <year>]`.

**Comment by thareUSGS** [comment]
I think we can call this approved. Using the OGC URI syntax as a guide, and others who have also approved, I think we can close this.
