### ISSUE TITLE
[WKT2/Proj6] : Mars radius

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/GDAL_scripts#40]
Issue: Mars has had a sorted use of target radius values. For example the MOLA and HRSC Team has defaulted to a "truncated" value of 3396000.0. The IAU has defined Mars as 3396190.0 and semi-minor radius of 3376200.00. In practice because many map projections only use the semi-major axis in their equations, it is common to see Mars set as a sphere of 3396190.0m. Then there is the PDS3 archives (e.g. HiRISE and CRISM) which because of the use of an ellipse in an ocentric system for the Equirectangular map projects, they set a locally calculated sphere at every 5 degrees of latitude.

How do we push for a single value for Mars, which is needed for an IAU map projection code (specifically 49900)?

**Comment by desruisseaux** [comment]
I'm not sure to understand the issue. Can the various radius be handle as different datum / ellipsoid? In such case, we would need different IAU codes for each definition having different radius of the same planet, and the WKT 2 strings of those definitions would have slightly different `DATUM` and `ELLIPSOID` elements.

**Comment by thareUSGS** [comment]
My thinking for now.

If we take the IAU paper as the rule, then should use the defined values as an ellipse:
semi-major radius (a_radius):  3396190.0m
                              (b_radius):  3396190.0m
semi-minor radius (c_radius):  3376200.0m

Note: because Mars is currently only defined as an ellipse (not a triaxial, using 3 unique radius values), the IAU calculated mean radius is not needed.

The problem here is that using Mars as an ellipse with ographic latitudes is well understood and used in most mapping applications. However, using Mars as an ellipse with ocentric latitudes is not well known and can often be incorrectly applied. This is why the HiRISE team and CRISM team set a locally calculated **spherical** radius for every 5 degrees of latitude (within their PDS3 archives).

Thus the defacto standard for Mars has been to continue to define as a sphere (using 3396190 or 3396000).

If I was able to make this call I would recommend using the IAU defined semi-major radius as a sphere (3396190.0m).
