### ISSUE TITLE
Grammer error in Projected CRS in .wtk

### ISSUE THREAD

**Issue by yamamoto-mitsuo** [USGS-Astrogeology/GDAL_scripts#8]
Excessive double quotes before every GEOGCS both in <[https://raw.githubusercontent.com/USGS-Astrogeology/GDAL_scripts/master/OGC_IAU2000_WKT_v2/IAU2000_v2.wkt](https://raw.githubusercontent.com/USGS-Astrogeology/GDAL_scripts/master/OGC_IAU2000_WKT_v2/IAU2000_v2.wkt)> and <[https://raw.githubusercontent.com/USGS-Astrogeology/GDAL_scripts/master/OGC_IAU2000_WKT_v2/IAU2009_v2.wkt](https://raw.githubusercontent.com/USGS-Astrogeology/GDAL_scripts/master/OGC_IAU2000_WKT_v2/IAU2009_v2.wkt)>.

According to "[Geographic information - Well-known text representation of coordinate reference systems](http://docs.opengeospatial.org/is/12-063r5/12-063r5.html)", the sole required separator between \<crs name\> and \<geogcs\> is \<wtk separator\>, which is comma, but in the two WTKs above the separator is ',"' (comma and double quote).

For example, in IAU2000_v2.wkt the actual text is

`19910,PROJCS["Mercury_Equidistant_Cylindrical","GEOGCS["Mercury 2000" ... `

where it should be

`19910,PROJCS["Mercury_Equidistant_Cylindrical",GEOGCS["Mercury 2000" ... `

**Comment by jlaura** [comment]
Pull requests are always welcome! Would you min submitting one with the
desired change?

Thanks,
Jay

**Comment by thareUSGS** [comment]
Let me know if this fixes the issue.

-Trent

**Comment by yamamoto-mitsuo** [comment]
I believe the issue is resolved.
Thank you for your responses. Thank you very much for creating and promoting the standard.

--
 Yamamoto, Mitsuo
 Lunar and Planetary Exploration Data Analysis Group
 Institute of Space and Astronautical Science
 Japan Aerospace Exploration Agency
